federation_version: =2.8.0
subscriptions:
  enabled: true
  protocols:
    - graphql-transport-ws
    - graphql-ws
subgraphs:
  workflows:
    routing_url: https://workflows.diamond.ac.uk/graphql
    schema:
      file: schema/workflows.graphql
    subscriptions:
      enabled: true
      protocols:
        - graphql-ws
  instrument_sessions:
    routing_url: https://instrument-sessions.diamond.ac.uk/api/graphql
    schema:
      file: schema/instrument_sessions.graphql
  samples:
    routing_url: https://sample-information.diamond.ac.uk/api/graphql
    schema:
      file: schema/samples.graphql
